apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: wordpress
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: wordpress
      port: 80
  virtualhost:
    fqdn: wordpress.
    tls:
      secretName: cert-manager/prod-wildcard-certs
