apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: guestbook
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: frontend
      port: 80
  virtualhost:
    fqdn: guestbook.
