apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testapp-wordpress-cluster02

labels:
  - pairs:
      env: lab
      cluster: cluster02.dc02-fd01.kubelab.app

resources:
  - github.com/malston/kustomize-apps/apps/bitnami-wordpress/base?ref=main
  - resource-quota.yaml

components:
- ../../../../../bases/bitnami-wordpress/components/ingress/contour

replacements:
- source:
    kind: HTTPProxy
    name: wordpress
    fieldPath: metadata.labels.cluster
  targets:
  - select:
      kind: HTTPProxy
      name: wordpress
    fieldPaths:
    - spec.virtualhost.fqdn
    options:
      delimiter: '.'
      index: 1
