apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wordpress
spec:
  gateways:
  - istio-gateways/istio-gateway
  hosts:
  - wordpress.
  http:
  - route:
    - destination:
        host: wordpress
        port:
          number: 80
