apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  gateways:
  - istio-gateways/istio-gateway
  hosts:
  - guestbook.
  http:
  - route:
    - destination:
        host: frontend
        port:
          number: 80
