apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
- ../../base
- namespace.yaml

configMapGenerator:
- name: parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.clusterDomain
  targets:
  - select:
      kind: HTTPProxy
      name: wordpress
    fieldPaths:
    - spec.virtualhost.fqdn
    options:
      delimiter: .
      index: 1

components:
- ../../components/ingress/contour

patches:
- patch: |
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: thin-disk
  target:
    kind: StatefulSet
    name: wordpress-mariadb
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: thin-disk
  target:
    kind: PersistentVolumeClaim
    name: wordpress