apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testapp-guestbook

labels:
- pairs:
    env: lab
    cluster: cluster02.dc02.fd01.kubelab.app

resources:
- github.com/malston/kustomize-apps/apps/guestbook/base?ref=main
- namespace.yaml

components:
- ../../../../../bases/guestbook/components/ingress/istio
- ../../../../../bases/guestbook/components/db/mongo

replacements:
- source:
    kind: VirtualService
    name: frontend
    fieldPath: metadata.labels.cluster
  targets:
  - select:
      kind: VirtualService
      name: frontend
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1

patches:
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: kubernetes-storage-policy
  target:
    kind: PersistentVolumeClaim
    name: mongo-pvc
