apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testapp-guestbook

resources:
- ../../../base
- namespace.yaml

components:
- ../../../components/ingress/istio
- ../../../components/db/mongo

configMapGenerator:
- name: parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.clusterDomain
  targets:
  - select:
      kind: VirtualService
      name: frontend
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1

patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/gb-frontend:v5
  target:
    kind: Deployment
    name: frontend
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/mongo:4.2
  target:
    kind: Deployment
    name: mongo
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/mongo:4.2
  target:
    kind: Deployment
    name: mongo-client
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: nas-ultra
  target:
    kind: PersistentVolumeClaim
    name: mongo-pvc
