apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: notImportantHere
replacements:
- source:
    kind: HTTPProxy
    name: wordpress
    fieldPath: metadata.labels.cluster
  targets:
  - select:
      kind: VirtualService
      name: wordpress
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1
