apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - redis-follower-deployment.yaml
  - redis-follower-service.yaml
  - redis-follower-pvc.yaml
  - redis-leader-deployment.yaml
  - redis-leader-service.yaml
  - redis-leader-pvc.yaml
  - redis-slave-service.yaml
