apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
- ../../base
- namespace.yaml

configMapGenerator:
- name: parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.clusterDomain
  targets:
  - select:
      kind: VirtualService
      name: wordpress
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1

components:
- ../../components/ingress/istio
- ../../components/storage/nas-performance
