apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testapp-wordpress

resources:
- github.com/malston/kustomize-apps/apps/bitnami-wordpress/base?ref=main
- resource-quota.yaml
- namespace.yaml

labels:
- includeSelectors: true
  pairs:
    env: lab
    cluster: cluster01.dc02.fd02.kubelab.app

secretGenerator:
- name: wordpress-mariadb
  namespace: wordpress
  behavior: replace
  literals:
    - mariadb-password=password
    - mariadb-root-password=password
- name: wordpress
  namespace: wordpress
  behavior: replace
  literals:
    - wordpress-password=password

patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/wordpress:6.4.3-debian-12-r18
  target:
    kind: Deployment
    name: wordpress
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/mariadb:11.2.3-debian-12-r4
  target:
    kind: StatefulSet
    name: wordpress-mariadb

transformers:
- ../../../../../bases/bitnami-wordpress/transformers/contour

components:
- ../../../../../bases/bitnami-wordpress/components/ingress/contour
