apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testapp-guestbook-cluster01

labels:
  - pairs:
      env: lab
      cluster: cluster01.dc02-fd01.kubelab.app

resources:
  - ../../../../../bases/guestbook/base/mongo

components:
- ../../../../../bases/guestbook/components/istio

replacements:
- source:
    kind: VirtualService
    name: frontend
    fieldPath: metadata.labels.cluster
  targets:
  - select:
      kind: VirtualService
      name: frontend
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1

patches:
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: kubernetes-storage-policy
  target:
    kind: PersistentVolumeClaim
    name: mongo-pvc
